# Generated by Django 3.2.2 on 2021-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('table_picture', models.ImageField(upload_to='hall_one_tables')),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=1000)),
                ('reserved', models.BooleanField()),
                ('count_of_chair', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hall [1]',
            },
        ),
        migrations.CreateModel(
            name='HallTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('table_picture', models.ImageField(upload_to='hall_two_tables')),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=1000)),
                ('reserved', models.BooleanField()),
                ('count_of_chair', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hall [2]',
            },
        ),
        migrations.CreateModel(
            name='VipHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('table_picture', models.ImageField(upload_to='vip_hall_tables')),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=1000)),
                ('reserved', models.BooleanField()),
                ('count_of_chair', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vip hall',
            },
        ),
    ]
