# Generated by Django 3.2.2 on 2021-05-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_now', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallone',
            options={'verbose_name_plural': 'Hall'},
        ),
    ]
