# Generated by Django 3.2.2 on 2021-05-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210510_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
