# Generated by Django 3.2.2 on 2021-05-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_hallone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HallOne',
            new_name='HallVip',
        ),
    ]
