# Generated by Django 3.2.2 on 2021-05-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_halltwo_viphall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallOne',
        ),
        migrations.DeleteModel(
            name='HallTwo',
        ),
        migrations.DeleteModel(
            name='VipHall',
        ),
    ]
